WIP API returns random movie
CraftAcademy/movie-selector-api-june-2020 pull request #6
Opened 2020-07-16 13:50 UTC by Alex-Bellamy

## https://www.pivotaltracker.com/story/show/173768613
## User Story
```
As a movie API
When the visitor clicks random
I want to return a random movie from the movie index
```
## Changes proposed in this pull request:
* 
## What I have learned working on this feature:
* 
## Packages/Gems added
-

2020-07-16 18:52 UTC, Cma-B approved these changes
it seems fine just remove WIP from the title!

2020-07-17 06:22 UTC, Odeane commented on spec/requests/api/v0/movies_collection_endpoint_spec.rb
> +    it 'is expected to return a movie' do
I think this should be ......'It is expected to return a movie "title". '

2020-07-17 07:40 UTC, emtalen requested changes
You need to adress the cache of the coverage and the randomising of a movie index, as i talked about with viktor yesterday afternoon

2020-07-17 07:40 UTC, emtalen commented on app/controllers/api/v1/movies_controller.rb
> +    random_movie = movies[rand(0..(movies.count))]
You need to add what I talked to Viktor about yesterday afternoon, that the movies.count has to be minus one

2020-07-17 07:40 UTC, emtalen commented on coverage/.resultset.json
>      "coverage": {
You need to clear the cache as i showed Viktor yesterday, so the coverage is not pushed up everytime

2020-07-17 07:40 UTC, emtalen commented on spec/requests/api/v1/user_can_randomise_a_movie_spec.rb
> +
When you correct the functionality in the controller you can change the response in the fixture to be one movie and then you can test more specific for that movie.

2020-07-17 08:05 UTC, emtalen reviewed
Just a minor fomatting issue now

2020-07-17 08:05 UTC, emtalen commented on config/routes.rb
>  end
Please mind the indentation, its 4 spaces here and not 2

2020-07-17 08:24 UTC, emtalen approved these changes

2020-07-17 08:24 UTC, merged